spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=WhiteBoard;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    connectionTimeout: 3000
    replyTimeout: 5000
  security:
    encrypt-algorithm: AES
    secret-key: mySecretKey

